// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Scheme.OrderStatusChanged
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class OrderStatusChange : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderStatusChange"",""namespace"":""Scheme.OrderStatusChanged"",""fields"":[{""name"":""orderId"",""type"":""string""},{""name"":""status"",""type"":{""type"":""record"",""name"":""Status"",""namespace"":""Scheme.OrderStatusChanged"",""fields"":[{""name"":""code"",""type"":""int""},{""name"":""name"",""type"":""string""}]}}]}");
		private string _orderId;
		private Scheme.OrderStatusChanged.Status _status;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderStatusChange._SCHEMA;
			}
		}
		public string orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public Scheme.OrderStatusChanged.Status status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderId;
			case 1: return this.status;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderId = (System.String)fieldValue; break;
			case 1: this.status = (Scheme.OrderStatusChanged.Status)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
